config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :devise_users do
      get 'login' => 'login#show', module: :devise_users
      get 'get_user' => 'get_user#show', module: :devise_users
    end
  end

  get '/devise_sample' =>  'devise_sample#show'

  devise_for :devise_users
  get 'dashboard' => 'dashboard#show'
  get '/auth/oauth2/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth0js' => 'auth0js#show'
  root 'home#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/devise_user.rb
class DeviseUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # , :omniauthable # omniauthable を指定すると omniauth による /auth/oauth が殺されてしまうので取ること

  # Auth0 への Automatic Migration 用のデータを作る
  def auth0_data
    {
      user_id: auth0_uid,
      email: email
    }.freeze
  end

  # Auth0 への Automatic Migration 用の user_id を作る
  def auth0_uid
    "devise_user|#{id}"
  end

  # Auth0 用に作った user_id から対応する DeviseUser を取り出す
  def self.find_by_auth0_uid(uid)
    provider, provider_uid = uid.to_s.match(/\A(\w+)\|(\d+)\z/)&.captures
    if provider
      case provider
        when 'devise_user'
          DeviseUser.find_by(id: provider_uid.to_i)
        else
          # Auth0 でソーシャルログインした場合、以下のように "provider|providerでのuid" というuidが取得できる
          # ex) facebook|0000000000000000
          # これを devise + omniauth-facebook で
          DeviseUser.find_by(provider: provider, uid: provider_uid)
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/devise_users/get_user_controller.rb
# Devise User の Auth0 へのAutomaticMigration サンプル
# Auth0 からの email と合わせに対してユーザーの有無を調べる
class Api::DeviseUsers::GetUserController < ApplicationController
  # TODO: IPアドレス制限。Auth0のカスタムデータベースアクセスのソースIPアドレスを確認してそこのみ許可する

  def show
    user = DeviseUser.find_by(email: params[:email])
    if user&.active_for_authentication?

      # 認証を通ったらこのデータベースが持っているユーザー情報を返す
      render json: user.auth0_data
    else
      render status: :not_found, json: {}
    end
  end
end

app/controllers/api/devise_users/login_controller.rb
# Devise User の Auth0 へのAutomaticMigration サンプル
# Auth0 へのログインがあった際、未登録の email のとき、こちらへ問い合わせを行う
# Devise のユーザーでパスワードがただしいか確認し、正しければユーザーIDを返す
class Api::DeviseUsers::LoginController < ApplicationController
  # TODO: IPアドレス制限。Auth0のカスタムデータベースアクセスのソースIPアドレスを確認してそこのみ許可する

  def show
    user = DeviseUser.find_by(email: params[:email])
    if user&.valid_for_authentication? { user.valid_password?(params[:password]) } &&
      user&.active_for_authentication?

      # 認証を通ったらこのデータベースが持っているユーザー情報を返す
      render json: user.auth0_data
    else
      render status: :not_found, json: {}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    # This stores all the user information that came from Auth0
    # and the IdP
    session[:userinfo] = request.env['omniauth.auth']

    # Redirect to the URL you want after successful auth
    redirect_to '/dashboard'
  end

  def failure
    # show a failure page or redirect to an error page
    @error_msg = request.params['message']
  end
end

app/controllers/auth0js_controller.rb
class Auth0jsController < ApplicationController
  def show
  end
end

app/controllers/concerns/secured.rb
module Secured
  extend ActiveSupport::Concern

  included do
    before_action :authenticate_omniauth?
  end

  def authenticate_omniauth?
    redirect_to '/' unless logged_in_using_omniauth?
  end

  # 現在 Auth0 でログインしたユーザーがDeviseからAuth0のAutomatic Migration機能で移行したユーザーの場合、
  # 対応する DeviseUser を取り出す
  def devise_user
    return @devise_user if defined?(@devise_user)
    @devise_user = if logged_in_using_omniauth?
                     provider = session[:userinfo]['provider']
                     if provider == 'auth0'
                       uid = session[:userinfo]['uid'] # ex) "auth0|5a84413df5c8213cb27be6cd" or "auth0|DeviseUser:1"
                       stripped_uid = uid.sub("#{provider}|", '')
                       DeviseUser.find_by_auth0_uid(stripped_uid)
                     end
                   end
  end

  def logged_in_using_omniauth?
    session[:userinfo].present?
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include Secured

  def show
    @devise_user = devise_user
  end
end

app/controllers/devise_sample_controller.rb
class DeviseSampleController < ApplicationController
  before_action :authenticate_devise_user!

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/helpers/api/devise_user_helper.rb
module Api::DeviseUserHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth0_helper.rb
module Auth0Helper
end

app/helpers/auth0js_helper.rb
module Auth0jsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devise_sample_helper.rb
module DeviseSampleHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def get_state
    state = SecureRandom.hex(24)
    session['omniauth.state'] = state

    state
  end
end

app/views/auth0/failure.html.erb
<%= @error_msg %>

app/views/auth0js/show.html.erb
<h1>Auth0js#show</h1>
<p>Find me in app/views/auth0js/show.html.erb</p>

<div id="js-auth0-lock"
     data-auth0-client-id="<%= Rails.application.secrets.auth0_client_id %>"
     data-auth0-domain="<%= Rails.application.secrets.auth0_domain %>">
  <button id="js-login-button">Login with Lock for Web</button>
  <p>Welcome <span id="js-nickname-area">Guest</span></p>
</div>

app/views/dashboard/show.html.erb
<h1>Dashboard#show</h1>
<p>Find me in app/views/dashboard/show.html.erb</p>

userinfo: <%= session[:userinfo].inspect %>

<hr>

DeviseUser: <%= @devise_user.inspect %>

app/views/devise_sample/show.html.erb
<h1>DeviseSample#show</h1>
<p>Find me in app/views/devise_sample/show.html.erb</p>
<%= button_to 'Logout', destroy_devise_user_session_path, method: :delete %>

app/views/home/show.html.erb
<section class="jumbotron text-center">
  <h2><img class="jumbo-thumbnail" src="https://cdn.auth0.com/styleguide/1.0.0/img/badge.svg"></h2>
  <h1>RoR Auth0 Sample</h1>
  <p>Step 1 - Login.</p>
  <a class="btn btn-success btn-lg" href="/auth/auth0">Login</a>
  <p>Or Lock v11 for Web</p>
  <%= link_to 'Login with Lock v11 for Web', auth0js_path %>
  <p>Or Devise</p>
  <%= link_to 'Login with Devise', devise_sample_path %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAuth0Sample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>